steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.api', '-t', 'gcr.io/$PROJECT_ID/stock-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - stock-api
      - --image=gcr.io/$PROJECT_ID/stock-api
      - --platform=managed
      - --region=asia-east1
      - --allow-unauthenticated